export const brands: Options[] = [
  { id: 1, label: "Arivo", value: "Arivo" },
  { id: 2, label: "Marshal", value: "Marshal" },
  { id: 3, label: "Formula", value: "Formula" },
  { id: 4, label: "Dynamo", value: "Dynamo" },
  { id: 5, label: "Landspider", value: "Landspider" },
  { id: 6, label: "Lassa", value: "Lassa" },
  { id: 7, label: "Kapsen", value: "Kapsen" },
  { id: 8, label: "Kumho", value: "Kumho" },
  { id: 9, label: "Falken", value: "Falken" },
  { id: 10, label: "Aplus", value: "Aplus" },
  { id: 11, label: "Michelin", value: "Michelin" },
  { id: 12, label: "Leao", value: "Leao" },
  { id: 13, label: "BFGoodrich", value: "BFGoodrich" },
  { id: 14, label: "LingLong", value: "LingLong" },
  { id: 15, label: "Centara", value: "Centara" },
  { id: 16, label: "Joyroad", value: "Joyroad" },
  { id: 17, label: "Barum", value: "Barum" },
  { id: 18, label: "GT_Radial", value: "GT_Radial" },
  { id: 19, label: "Armstrong", value: "Armstrong" },
  { id: 20, label: "Kormoran", value: "Kormoran" },
  { id: 21, label: "Ikon_Tyres", value: "Ikon_Tyres" },
  { id: 22, label: "Headway", value: "Headway" },
  { id: 23, label: "Nokian_Nordman", value: "Nokian_Nordman" },
  { id: 24, label: "Delmax", value: "Delmax" },
  { id: 25, label: "Altenzo", value: "Altenzo" },
  { id: 26, label: "Firestone", value: "Firestone" },
  { id: 27, label: "Cachland", value: "Cachland" },
  { id: 28, label: "Avatyre", value: "Avatyre" },
  { id: 29, label: "HiFly", value: "HiFly" },
  { id: 30, label: "Cooper", value: "Cooper" },
  { id: 31, label: "Belshina", value: "Belshina" },
  { id: 32, label: "Antares_tires", value: "Antares_tires" },
  { id: 33, label: "Contyre", value: "Contyre" },
  { id: 34, label: "Laufenn", value: "Laufenn" },
  { id: 35, label: "Goodride", value: "Goodride" },
  { id: 36, label: "Gislaved", value: "Gislaved" },
  { id: 37, label: "Matador", value: "Matador" },
  { id: 38, label: "Goodyear", value: "Goodyear" },
  { id: 39, label: "Forward", value: "Forward" },
  { id: 40, label: "Evergreen", value: "Evergreen" },
  { id: 41, label: "Delinte", value: "Delinte" },
  { id: 42, label: "Atlander", value: "Atlander" },
  { id: 43, label: "Gripmax", value: "Gripmax" },
  { id: 44, label: "Compasal", value: "Compasal" },
  { id: 45, label: "Nokian_Tyres", value: "Nokian_Tyres" },
  { id: 46, label: "Pirelli", value: "Pirelli" },
  { id: 47, label: "Amtel", value: "Amtel" },
  { id: 48, label: "Aeolus", value: "Aeolus" },
  { id: 49, label: "KingStar", value: "KingStar" },
  { id: 50, label: "Nordman", value: "Nordman" },
  { id: 51, label: "Triangle", value: "Triangle" },
  { id: 52, label: "Kleber", value: "Kleber" },
  { id: 53, label: "Hankook", value: "Hankook" },
  { id: 54, label: "Nankang", value: "Nankang" },
  { id: 55, label: "Haida", value: "Haida" },
  { id: 56, label: "Austone", value: "Austone" },
  { id: 57, label: "Cordiant", value: "Cordiant" },
  { id: 58, label: "iLINK", value: "iLINK" },
  { id: 59, label: "DoubleStar", value: "DoubleStar" },
  { id: 60, label: "Yokohama", value: "Yokohama" },
  { id: 61, label: "Bridgestone", value: "Bridgestone" },
  { id: 62, label: "Nexen", value: "Nexen" },
  { id: 63, label: "Mirage", value: "Mirage" },
  { id: 64, label: "Sailun", value: "Sailun" },
  { id: 65, label: "General_Tire", value: "General_Tire" },
  { id: 66, label: "Dunlop", value: "Dunlop" },
  { id: 67, label: "Fortune", value: "Fortune" },
  { id: 68, label: "Firemax", value: "Firemax" },
  { id: 69, label: "Landsail", value: "Landsail" },
  { id: 70, label: "Jinyu", value: "Jinyu" },
  { id: 71, label: "Bearway", value: "Bearway" },
  { id: 72, label: "Boto", value: "Boto" },
  { id: 73, label: "Imperial", value: "Imperial" },
  { id: 74, label: "Maxxis", value: "Maxxis" },
  { id: 75, label: "Continental", value: "Continental" }
];


export const seasonality: Options[] = [
  { id: 1, label: "Летние", value: "Летние" },
  { id: 2, label: "Зимние", value: "Зимные" },
  { id: 3, label: "Всесезонные", value: "Всесезонные" },
];

export const index_of_speed: Options[] = [
  { id: 1, label: "L (120 km/h)", value: "L" },
  { id: 2, label: "M (130 km/h)", value: "M" },
  { id: 3, label: "N (140 km/h)", value: "N" },
  { id: 4, label: "P (150 km/h)", value: "P" },
  { id: 5, label: "Q (160 km/h)", value: "Q" },
  { id: 6, label: "R (170 km/h)", value: "R" },
  { id: 7, label: "S (180 km/h)", value: "S" },
  { id: 8, label: "T (190 km/h)", value: "T" },
  { id: 9, label: "U (200 km/h)", value: "U" },
  { id: 10, label: "H (210 km/h)", value: "H" },
  { id: 11, label: "V (240 km/h)", value: "V" },
  { id: 12, label: "W (270 km/h)", value: "W" },
  { id: 13, label: "Y (300 km/h)", value: "Y" },
  { id: 14, label: "Z (300+ km/h)", value: "Z" },
];
